version: "3.7"

services:

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - 80:80
    volumes: 
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  # Path to HAProxy config
    networks:
      - frontend
      - backend

  frontend1:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 3000:80
    networks:
      - frontend

  auth1:
    build:
      context: ./backend/auth
      dockerfile: Dockerfile
    container_name: auth
    networks:
      - backend

  items1:
    build:
      context: ./backend/items
      dockerfile: Dockerfile
    container_name: items
    ports:
      - "3003:3003"
    networks:
      - backend

  discounts1:
    build:
      context: ./backend/discounts
      dockerfile: Dockerfile
    container_name: discount
    ports:
      - "3002:3002"
    networks:
      - backend


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge