- name: Install Docker
  apt:
    name: docker
    state: present
    update_cache: yes
  become: true

- name: Clone repository
  git:
    repo: https://github.com/Tassianna/restaurant-app.git
    dest: ./
  become: true

# inventory_hostname
- name: Copy Docker Compose file for relevant service and overwrite original
  copy:
    src: "../templates/docker-compose.yml"
    dest: "~/restaurant-app/docker-compose.yml"

- name: Build and Compose containers
  docker_compose:
    project_src: ~/restautant-app