---
- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Docker images
      docker_image:
        name: "{{ docker_image }}"
        source: pull

- hosts: haproxy
  become: yes
  tasks:
    - name: copy haproxy.cfg
      template:
        src: haproxy.cfg.j2
        dest: /haproxy.cfg

- hosts: all
  become: yes
  tasks:
    - name: Run the images
      docker_container:
        name: "{{ name }}"
        image: "{{ docker_image }}"
        ports: "{{ ports | default([]) }}"
        state: started